from importlib import import_module

from django.db import migrations
from django.utils import timezone


seed_helpers = import_module(
    "apps.certifications.migrations.0006_seed_certificate_starters"
)
element = seed_helpers.element
layout = seed_helpers.layout

TEMPLATE_NAME = "Airads College Official"
STARTER_KEY = "airads-college-official"


def airads_default_definition():
    blue = "#0c4da2"
    red = "#ed1c24"
    green = "#008b4b"
    ink = "#172033"
    muted = "#536277"

    return {
        "name": TEMPLATE_NAME,
        "orientation": "portrait",
        "width": 210,
        "height": 297,
        "layout": layout(
            "#fffefa",
            [
                element(
                    "airads-border-blue",
                    "shape",
                    4,
                    4,
                    202,
                    289,
                    shape="rectangle",
                    z_index=0,
                    locked=True,
                    name="Outer blue border",
                    styles={
                        "fill": "transparent",
                        "stroke": blue,
                        "strokeWidth": 3,
                    },
                ),
                element(
                    "airads-border-red",
                    "shape",
                    7.5,
                    7.5,
                    195,
                    282,
                    shape="rectangle",
                    z_index=1,
                    locked=True,
                    name="Middle red border",
                    styles={
                        "fill": "transparent",
                        "stroke": red,
                        "strokeWidth": 2,
                    },
                ),
                element(
                    "airads-border-green",
                    "shape",
                    10.5,
                    10.5,
                    189,
                    276,
                    shape="rectangle",
                    z_index=2,
                    locked=True,
                    name="Inner green border",
                    styles={
                        "fill": "transparent",
                        "stroke": green,
                        "strokeWidth": 1.5,
                    },
                ),
                element(
                    "airads-crest",
                    "image",
                    17,
                    18,
                    34,
                    34,
                    "/static/airads-logo.png",
                    z_index=5,
                    assetUrl="/static/airads-logo.png",
                    name="Airads crest",
                    styles={"objectFit": "contain", "opacity": 1},
                ),
                element(
                    "airads-institute-name",
                    "text",
                    54,
                    17,
                    138,
                    17,
                    "AFRICAN INSTITUTE",
                    font_size=24,
                    font_weight=800,
                    color=red,
                    align="left",
                    z_index=5,
                    name="Institution name",
                    styles={
                        "fontFamily": "Georgia",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 17,
                        "maxFontSize": 24,
                    },
                ),
                element(
                    "airads-institute-subtitle",
                    "text",
                    55,
                    34,
                    137,
                    10,
                    "OF RESEARCH AND DEVELOPMENT STUDIES",
                    font_size=10,
                    font_weight=700,
                    color=blue,
                    align="left",
                    z_index=5,
                    name="Institution subtitle",
                    styles={
                        "fontFamily": "Georgia",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 7,
                        "maxFontSize": 10,
                    },
                ),
                element(
                    "airads-college-name",
                    "text",
                    55,
                    45,
                    137,
                    11,
                    "(AIRADS COLLEGE)",
                    font_size=14,
                    font_weight=800,
                    color=red,
                    z_index=5,
                    name="Airads College name",
                    styles={"fontFamily": "Georgia"},
                ),
                element(
                    "airads-campus",
                    "dynamic_text",
                    55,
                    56,
                    137,
                    7,
                    "{{campus}}",
                    font_size=9,
                    font_weight=700,
                    color=blue,
                    z_index=5,
                    name="Campus",
                    styles={
                        "textTransform": "uppercase",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 6,
                        "maxFontSize": 9,
                        "letterSpacing": 0.8,
                    },
                ),
                element(
                    "airads-header-red-line",
                    "line",
                    18,
                    67,
                    174,
                    2,
                    z_index=4,
                    name="Header red rule",
                    styles={"stroke": red, "strokeWidth": 2},
                ),
                element(
                    "airads-header-blue-line",
                    "line",
                    18,
                    70,
                    174,
                    1,
                    z_index=4,
                    name="Header blue rule",
                    styles={"stroke": blue, "strokeWidth": 0.8},
                ),
                element(
                    "airads-certificate-title",
                    "text",
                    22,
                    74,
                    166,
                    22,
                    "Certificate of Completion",
                    font_size=30,
                    font_weight=700,
                    color=ink,
                    z_index=6,
                    name="Certificate title",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 22,
                        "maxFontSize": 30,
                    },
                ),
                element(
                    "airads-title-blue-line",
                    "line",
                    18,
                    97,
                    174,
                    1,
                    z_index=4,
                    name="Title blue rule",
                    styles={"stroke": blue, "strokeWidth": 0.8},
                ),
                element(
                    "airads-title-red-line",
                    "line",
                    18,
                    100,
                    174,
                    2,
                    z_index=4,
                    name="Title red rule",
                    styles={"stroke": red, "strokeWidth": 2},
                ),
                element(
                    "airads-watermark-outer",
                    "shape",
                    51,
                    105,
                    108,
                    108,
                    shape="circle",
                    z_index=2,
                    locked=True,
                    name="Airads watermark ring",
                    styles={
                        "fill": "transparent",
                        "stroke": blue,
                        "strokeWidth": 4,
                        "opacity": 0.06,
                    },
                ),
                element(
                    "airads-watermark-inner",
                    "shape",
                    60,
                    114,
                    90,
                    90,
                    shape="circle",
                    z_index=2,
                    locked=True,
                    name="Airads watermark inner ring",
                    styles={
                        "fill": "#ffffff",
                        "stroke": red,
                        "strokeWidth": 2,
                        "opacity": 0.05,
                    },
                ),
                element(
                    "airads-watermark-name",
                    "text",
                    56,
                    142,
                    98,
                    24,
                    "AIRADS",
                    font_size=40,
                    font_weight=800,
                    color=red,
                    z_index=2,
                    locked=True,
                    name="Airads watermark",
                    styles={
                        "fontFamily": "Georgia",
                        "opacity": 0.055,
                        "letterSpacing": 2,
                    },
                ),
                element(
                    "airads-awarded-to",
                    "text",
                    42,
                    105,
                    126,
                    9,
                    "Awarded to",
                    font_size=14,
                    font_weight=400,
                    color=muted,
                    z_index=7,
                    name="Awarded to label",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                    },
                ),
                element(
                    "airads-student-name",
                    "dynamic_text",
                    22,
                    116,
                    166,
                    20,
                    "{{student_name}}",
                    font_size=27,
                    font_weight=700,
                    color=ink,
                    z_index=7,
                    name="Student name",
                    styles={
                        "fontFamily": "Georgia",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 15,
                        "maxFontSize": 27,
                    },
                ),
                element(
                    "airads-student-line",
                    "line",
                    24,
                    137,
                    162,
                    1,
                    z_index=6,
                    name="Student name rule",
                    styles={"stroke": "#5c6675", "strokeWidth": 0.7},
                ),
                element(
                    "airads-completion-copy",
                    "text",
                    26,
                    145,
                    158,
                    10,
                    "having successfully completed the requirements for",
                    font_size=12,
                    font_weight=400,
                    color=muted,
                    z_index=7,
                    name="Completion statement",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                    },
                ),
                element(
                    "airads-program-title",
                    "dynamic_text",
                    25,
                    158,
                    160,
                    24,
                    "{{program_title}}",
                    font_size=21,
                    font_weight=700,
                    color=blue,
                    z_index=7,
                    name="Course title",
                    styles={
                        "fontFamily": "Georgia",
                        "autoShrink": True,
                        "minFontSize": 12,
                        "maxFontSize": 21,
                        "lineHeight": 1.05,
                    },
                ),
                element(
                    "airads-completion-date",
                    "dynamic_text",
                    31,
                    186,
                    148,
                    10,
                    "Completed on {{completion_date}}",
                    font_size=11,
                    font_weight=400,
                    color=muted,
                    z_index=7,
                    name="Completion date",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 8,
                        "maxFontSize": 11,
                    },
                ),
                element(
                    "airads-recognition-copy",
                    "text",
                    27,
                    199,
                    156,
                    12,
                    "In recognition of the successful completion of the prescribed course of study.",
                    font_size=9,
                    font_weight=400,
                    color=muted,
                    z_index=7,
                    name="Recognition statement",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                        "lineHeight": 1.25,
                    },
                ),
                element(
                    "airads-principal-name",
                    "dynamic_text",
                    18,
                    225,
                    63,
                    9,
                    "{{principal_name}}",
                    font_size=9,
                    font_weight=600,
                    color=ink,
                    z_index=7,
                    name="Principal name",
                    styles={
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 6,
                        "maxFontSize": 9,
                    },
                ),
                element(
                    "airads-principal-line",
                    "line",
                    20,
                    235,
                    59,
                    1,
                    z_index=6,
                    name="Principal signature line",
                    styles={"stroke": ink, "strokeWidth": 0.8},
                ),
                element(
                    "airads-principal-role",
                    "text",
                    20,
                    238,
                    59,
                    9,
                    "Principal",
                    font_size=9,
                    font_weight=700,
                    color=ink,
                    z_index=7,
                    name="Principal role",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                    },
                ),
                element(
                    "airads-manager-line",
                    "line",
                    131,
                    235,
                    59,
                    1,
                    z_index=6,
                    name="Manager signature line",
                    styles={"stroke": ink, "strokeWidth": 0.8},
                ),
                element(
                    "airads-manager-role",
                    "text",
                    130,
                    238,
                    61,
                    13,
                    "General Manager\n(Academic Affairs)",
                    font_size=8,
                    font_weight=700,
                    color=ink,
                    z_index=7,
                    name="Manager role",
                    styles={
                        "fontFamily": "Georgia",
                        "fontStyle": "italic",
                        "lineHeight": 1.05,
                    },
                ),
                element(
                    "airads-seal",
                    "shape",
                    88,
                    225,
                    34,
                    34,
                    shape="circle",
                    z_index=6,
                    name="Official seal",
                    styles={
                        "fill": red,
                        "stroke": "#b20f17",
                        "strokeWidth": 1.2,
                        "opacity": 0.96,
                    },
                ),
                element(
                    "airads-seal-inner",
                    "shape",
                    92,
                    229,
                    26,
                    26,
                    shape="circle",
                    z_index=7,
                    name="Official seal inner ring",
                    styles={
                        "fill": "transparent",
                        "stroke": "#ffffff",
                        "strokeWidth": 1.2,
                        "opacity": 0.9,
                    },
                ),
                element(
                    "airads-seal-label",
                    "text",
                    92,
                    237,
                    26,
                    10,
                    "OFFICIAL\nSEAL",
                    font_size=8,
                    font_weight=800,
                    color="#ffffff",
                    z_index=8,
                    name="Official seal label",
                    styles={"lineHeight": 1.05, "letterSpacing": 0.5},
                ),
                element(
                    "airads-qr",
                    "qr_code",
                    18,
                    257,
                    22,
                    22,
                    "{{verification_url}}",
                    z_index=7,
                    name="Verification QR code",
                    styles={
                        "foreground": blue,
                        "background": "#ffffff",
                        "errorCorrection": "M",
                        "padding": 1,
                        "borderColor": blue,
                        "borderWidth": 0.5,
                    },
                ),
                element(
                    "airads-issued-date",
                    "dynamic_text",
                    45,
                    257,
                    66,
                    8,
                    "Issued {{issue_date}}",
                    font_size=8,
                    font_weight=500,
                    color=muted,
                    align="left",
                    z_index=7,
                    name="Issue date",
                    styles={
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 6,
                        "maxFontSize": 8,
                    },
                ),
                element(
                    "airads-validity-note",
                    "text",
                    45,
                    268,
                    77,
                    9,
                    "Verify with the QR code. Not valid without the official seal.",
                    font_size=7,
                    font_weight=500,
                    color=muted,
                    align="left",
                    z_index=7,
                    name="Validity note",
                    styles={"lineHeight": 1.1},
                ),
                element(
                    "airads-certificate-number",
                    "dynamic_text",
                    123,
                    262,
                    68,
                    9,
                    "Certificate No. {{serial_number}}",
                    font_size=8,
                    font_weight=600,
                    color=ink,
                    align="right",
                    z_index=7,
                    name="Certificate number",
                    styles={
                        "singleLine": True,
                        "autoShrink": True,
                        "minFontSize": 6,
                        "maxFontSize": 8,
                    },
                ),
            ],
            accent=red,
            border=blue,
        ),
    }


def seed_airads_default(apps, schema_editor):
    CertificateTemplate = apps.get_model(
        "certifications", "CertificateTemplate"
    )
    CertificateTemplateVersion = apps.get_model(
        "certifications", "CertificateTemplateVersion"
    )
    definition = airads_default_definition()

    CertificateTemplate.objects.filter(is_default=True).update(is_default=False)
    template, _ = CertificateTemplate.objects.update_or_create(
        name=definition["name"],
        is_starter=True,
        defaults={
            "owner": None,
            "is_default": True,
            "visibility": "system",
            "status": "published",
            "current_version_number": 1,
            "metadata": {
                "starterKey": STARTER_KEY,
                "description": "Official Airads College portrait certificate.",
            },
        },
    )
    CertificateTemplateVersion.objects.update_or_create(
        template=template,
        version_number=1,
        defaults={
            "orientation": definition["orientation"],
            "width_mm": definition["width"],
            "height_mm": definition["height"],
            "layout": definition["layout"],
            "created_by": None,
            "is_published": True,
            "published_at": timezone.now(),
        },
    )


def remove_airads_default(apps, schema_editor):
    CertificateTemplate = apps.get_model(
        "certifications", "CertificateTemplate"
    )
    CertificateTemplateAssignment = apps.get_model(
        "certifications", "CertificateTemplateAssignment"
    )
    template = CertificateTemplate.objects.filter(
        name=TEMPLATE_NAME,
        is_starter=True,
    ).first()
    if not template:
        return

    CertificateTemplateAssignment.objects.filter(
        template_version__template=template
    ).delete()
    template.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("certifications", "0008_seed_more_certificate_templates"),
    ]

    operations = [
        migrations.RunPython(seed_airads_default, remove_airads_default),
    ]
